---
title: "EDA"
format: pdf
editor: visual
---

## 

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
library(qtl2)
library(janitor)
#fertility_data <- read.csv("~/pstat100/final_project/data/fertility_infant_mortality/fertility_data.csv")
#infant_data <- read.csv("~/pstat100/final_project/data/fertility_infant_mortality/infant_mortality_biannual_data.csv")
#maternal_mort <- read.csv("~/Maternal_Death_Counts.csv")

fertility_data <- read.csv("~/Desktop/UCSB/PSTAT100-final/fertility_data.csv")
infant_mortality_biannual_data <- read.csv("~/Desktop/UCSB/PSTAT100-final/infant_mortality_biannual_data.csv")
#maternal_mort <- read.csv("~/Desktop/UCSB/PSTAT100-final/Maternal_Death_Counts.csv")
maternal_mort <- read.csv("~/Desktop/UCSB/PSTAT100-final/VSRR_Provisional_Maternal_Death_Counts_and_Rates.csv")
```

```{r}
maternal_mort1 <- maternal_mort |>
  pivot_wider(names_from= Group, values_from=Subgroup)

maternal_mort1 <- maternal_mort1 %>% 
  clean_names()

maternal_byAge <- maternal_mort1 |> filter(!is.na(age))
maternal_byRace <- maternal_mort1 |> filter(!is.na(race_and_hispanic_origin)) |>
  rename("RaceEth"=race_and_hispanic_origin)

head(maternal_byAge)
head(maternal_byRace)
okabe <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#D55E00", "#CC79A7")

maternal_byRace |> ggplot(aes(x=year_of_death, y=maternal_mortality_rate, color=RaceEth)) +
  geom_point()
maternal_byRace |> ggplot(aes(x=live_births, y=maternal_deaths, color=RaceEth)) +
  geom_point() + 
  scale_color_manual(values=okabe)

```

```{r}
ggplot(fertility_data, aes(x = year, y = births_total, group = state, color = state)) +
   geom_point()
```

```{r}
fertility_years <- fertility_data %>% 
  pivot_longer(cols = starts_with("births_age"), names_to = "age_group", values_to = "births")

ggplot(fertility_years, aes(x = fct_reorder(state, -births), y = births, fill = age_group)) +
  geom_bar(stat = "identity", position = "stack") + coord_flip()

ggplot(fertility_years, aes(x = year, y = births, color = age_group)) +
  geom_point()
```

```{r}
fertility_edu <- fertility_years %>% 
  pivot_longer(cols = c("births_nohs", "births_hs", "births_somecoll", "births_coll"), names_to = "edu_backg", values_to = "edu_births")

ggplot(fertility_edu, aes(x = fct_reorder(state, -edu_births), y = edu_births, fill = edu_backg)) +
  geom_bar(stat = "identity", position = "stack") + coord_flip()

fertility_edu_avg <- fertility_edu %>% 
  group_by(year, edu_backg) %>% 
  summarise(avg_births_edu = mean(edu_births, na.rm = TRUE)) %>% 
  ungroup()

ggplot(fertility_edu, aes(x = year, y = edu_births, color = edu_backg)) +
 geom_point()

ggplot(fertility_edu_avg, aes(x = year, y = avg_births_edu, color = edu_backg, group = edu_backg)) + geom_point() + geom_line()
```

```{r}
fertility_eth <- fertility_edu %>% 
  pivot_longer(cols = c("births_nhblack", "births_nhwhite", "births_hisp", "births_otherraceeth"), names_to = "ethnicity", values_to = "eth_births")

ggplot(fertility_eth, aes(x = ethnicity, y = eth_births, fill = ethnicity)) +
  geom_bar(stat = "identity", position = "stack") + coord_flip()

fertility_eth_avg <- fertility_eth %>% 
  group_by(year, ethnicity) %>% 
  summarise(avg_births = mean(eth_births, na.rm = TRUE)) %>% 
  ungroup()

ggplot(fertility_eth_avg, aes(x = year, y = avg_births, color = ethnicity, group = ethnicity)) + geom_point() + geom_line()

ggplot(fertility_eth, aes(x = year, y = eth_births, color = ethnicity)) + geom_point()
```

```{r}
fertility_marriage <- fertility_eth %>% 
  pivot_longer(cols = c("births_married", "births_unmarried"), names_to = "marital_status", values_to = "marital_births")

fertility_mar_avg <- fertility_marriage %>% 
  group_by(year, marital_status) %>% 
  summarise(avg_births_mar = mean(marital_births, na.rm = TRUE)) %>% 
  ungroup()

ggplot(fertility_mar_avg, aes(x = year, y = avg_births_mar, color = marital_status, group = marital_status)) + geom_point() + geom_line()
```

```{r}
fertility_medic <- fertility_data %>% 
  pivot_longer(cols = c("births_medicaid", "births_nonmedicaid"), names_to = "health_status", values_to = "births_health")

ggplot(fertility_medic, aes(x = fct_reorder(state, -births_health), y = births_health, fill = health_status)) +
  geom_bar(stat = "identity", position = "stack") + coord_flip()

fertility_med_avg <- fertility_medic %>% 
  group_by(year, health_status) %>% 
  summarise(avg_births_med = mean(births_health, na.rm = TRUE)) %>% 
  ungroup()

ggplot(fertility_med_avg, aes(x = year, y = avg_births_med, color = health_status, group = health_status)) + geom_point() + geom_line()


```

```{r}
ggplot(infant_mortality_biannual_data, aes(x = deaths_total)) +
  geom_histogram(bins = 30)
```

```{r}
#create proportions for everything, regraph 
#sum bm_code into 2 chunks for fertility
mortality_ethnicity <- infant_mortality_biannual_data %>% 
  pivot_longer(cols = c(deaths_nhblack, deaths_nhwhite, deaths_hisp, deaths_otherraceeth), names_to = "Race", values_to = "Deaths") %>% 
  mutate(deaths_prop = Deaths/deaths_total)

ggplot(mortality_ethnicity, aes(x = Race, y = deaths_prop, fill = Race)) + geom_boxplot()

ggplot(mortality_ethnicity, aes(x = Race, y = deaths_prop, fill = Race)) + geom_bar(stat = "identity")
```

```{r}
infant_mortality_biannual_data <- infant_mortality_biannual_data %>% 
  mutate(deaths_postneo = deaths_total - deaths_neo)

mortality_neo <- infant_mortality_biannual_data %>% 
  pivot_longer(cols = c(deaths_neo, deaths_postneo), names_to = "Death_type", values_to = "count")

ggplot(mortality_neo, aes(x = year, y = count, fill = Death_type)) +
  geom_bar(stat = "identity")
```

```{r}
mortality_con <- infant_mortality_biannual_data %>% 
  pivot_longer(cols = c(deaths_con, deaths_noncon), names_to = "Cause", values_to = "con_deaths")

ggplot(mortality_con, aes(x = year, y = con_deaths, fill = Cause)) + geom_bar(stat = "identity", position = "dodge")
```

```{r}
mortality_avg <- infant_mortality_biannual_data %>% 
  group_by(year, state) %>% 
  summarise(avg_deaths = mean(deaths_total, na.rm = TRUE)) %>% 
  ungroup()

ggplot(infant_mortality_biannual_data, aes(x = year, y = deaths_total, group = state, color = state)) + geom_line() + geom_point()

infant_mortality_biannual_data <- infant_mortality_biannual_data %>% 
  mutate(across(c(deaths_nhblack, deaths_nhwhite, deaths_hisp), \(x) replace_na(x, 0)))

mortality <- infant_mortality_biannual_data %>%
  pivot_longer(cols = c(deaths_nhblack, deaths_nhwhite, deaths_hisp, deaths_otherraceeth), names_to = "Race", values_to = "deaths")

ggplot(mortality, aes(x = fct_reorder(state, -deaths), y = deaths, fill = Race)) +
  geom_bar(stat = "identity", position = "stack") + coord_flip()

mortality_avg_eth <- mortality_ethnicity %>% 
  group_by(year, Race) %>% 
  summarise(avg_deaths = mean(Deaths, na.rm = TRUE)) %>% 
  ungroup()

ggplot(mortality_avg_eth, aes(x = year, y = avg_deaths, group = Race, color = Race)) + geom_line() + geom_point()

ggplot(mortality, aes(x = year, y = deaths, color = Race, group = Race)) +
  geom_line() + geom_point()
```

```{r}

```
