---
title: "Project_Text"
author: Leslie Cervantes Rivera & Kevin Le
format: pdf
editor: visual
---

# Background

The Infant Mortality and Fertility Rates Dataset provides data on infant mortality rates (measured as the number of infant deaths per 1,000 live births) and fertility rates (measured as the number of births per 1,000 women per year) across U.S. states. The Infant Mortality Dataset covers the years 2003 to 2023, while the Fertility Rates Dataset spans 2016 to 2023.

Infant mortality refers to the death of baby that occurs before their first birthday. It is a key indicator of a population's overall health, reflecting the social, economic, and healthcare conditions within a state. High infant mortality rates could indicate insufficient healthcare access or inequalities in medical services, particularly in low-income and rural areas. Over the years, improvements in screening and treatment for illnesses, better obstetric management, and neonatal care have contributed in the declining of infant mortality rates, but disparities still exist within state and demographic groups. (<https://www.vcuhealth.org/news/infant-mortality-rates-declining-but-sudden-unexpected-infant-death-is-on-the-rise/#:~:text=Wolf%20attributes%20declining%20overall%20infant,media%20on%20infant%20sleep%20practices.>) (<https://www.nichd.nih.gov/health/topics/infant-mortality/topicinfo>)

Fertility rate represents the total number of children a woman has during her reproductive years. It plays a crucial role in population growth and demographical planning, influencing services such as education, healthcare, and workforce development. From 2007 to 2022, the fertility rate has dropped by about 19%, influenced by the health of the economy, social, health, and historical events. These changes have long-term implications, as it leads to an aging population, smaller workforce, and economic strain on government budgets. (<https://www.britannica.com/topic/fertility-rate>) (<https://www.northwell.edu/news/the-latest/us-fertility-rate-decline-impact#:~:text=After%20a%20few%20decades%20of,historical%20events%E2%80%94affect%20family%20sizes.>)

The Maternal Mortality dataset provides national-level provisional counts of deaths among women who die during pregnancy or within 42 days of the termination of pregnancy, but not from accidental or incidental causes. These deaths are based on death records that have been received and processed by the National Center for Health Statistics (NCHS) as of a specified cutoff date. The dataset includes deaths among U.S. residents that occurred within the 50 states and the District of Columbia. Maternal mortality rates are calculated as deaths per 100,000 live births.

## Data Sources

The datasets come from the Centers for Disease Control and Prevention (CDC), collected from anywhere a person receives healthcare. This may lead to limitations as it is up to the city, county, and state to decide what information is collected, and how and when it can be shared by the CDC. (<https://archive.cdc.gov/www_cdc_gov/surveillance/data-modernization/basics/where_does_our_data_come_from.html>)

The NCHS obtains maternal death records from state vital registration offices through the Vital Statistics Cooperative Program. The estimates of maternal mortalities are derived from final mortality data for the years 2019 to 2021, and provisional data for the years 2022 to 2024. Provisional data reflects counts based on reports that are still being processed, while finalized data represents more complete counts of maternal deaths after thorough review and analysis. (Provisional Maternal Death Counts) https://www.cdc.gov/nchs/nvss/vsrr/provisional-maternal-deaths.htm

### Infant mortality

| Variable Name | Meaning |
|----|----|
| `bacode` | Biannual code. 1 means data aggregated from January 1 through June 30, 2 means data from July 1 through December 31. |
| `births_nhblack` | Number of births to non-Hispanic Black mothers |
| `births_nhwhite` | Number of births to non-Hispanic White mothers |
| `births_hisp` | Number of births to Hispanic mothers of any race |
| `births_otherraceeth` | Number of births to mothers of other races/ethnicities |
| `births_total` | Total number of births across all racial/ethnic groups |
| `deaths_hisp` | Number of deaths among Hispanic population of any race |
| `deaths_con` | Number of congenital-related deaths (present at birth) |
| `deaths_noncon` | Number of non-congenital deaths |
| `deaths_neo` | Number of neonatal deaths (within first 28 days of life) |

### Fertility

| Variable Name         | Meaning                                            |
|-----------------------|----------------------------------------------------|
| `births_age1524`      | Births to mothers aged 15-24                       |
| `births_age2534`      | Births to mothers aged 25-34                       |
| `births_age3544`      | Births to mothers aged 35-44                       |
| `pop_age1524`         | Population aged 15-24 (women age 15-54 population) |
| `pop_age2534`         | Population aged 25-34 (women age 15-54 population) |
| `pop_age3544`         | Population aged 35-44 (women age 15-54 population) |
| `births_nhblack`      | Births to non-Hispanic Black mothers               |
| `births_nhwhite`      | Births to non-Hispanic White mothers               |
| `births_hisp`         | Births to Hispanic mothers                         |
| `births_otherraceeth` | Births to mothers of other races/ethnicities       |
| `births_total`        | Total births across all categories                 |

#### Education

| Variable Name | Meaning |
|----|----|
| `births_nohs` | Births to mothers without high school education |
| `births_hs` | Births to mothers with high school education |
| `births_somecoll` | Births to mothers with some college education |
| `births_coll` | Births to mothers with college degree |
| `pop_nohs` | Population without high school education (women age 15-54 population) |
| `pop_hs` | Population with high school education (women age 15-54 population) |
| `pop_somecoll` | Population with some college education (women age 15-54 population) |
| `pop_coll` | Population with college degree (women age 15-54 population) |

#### Status

| Variable Name | Meaning |
|----|----|
| `births_married` | Births to married mothers |
| `births_unmarried` | Births to unmarried mothers |
| `pop_married` | Married population (women age 15-54 population) |
| `pop_unmarried` | Unmarried population (women age 15-54 population) |
| `births_medicaid` | Births covered by Medicaid |
| `births_nonmedicaid` | Births not covered by Medicaid |
| `pop_medicaid` | Population covered by Medicaid (women age 15-54 population) |
| `pop_nonmedicaid` | Population not covered by Medicaid (women age 15-54 population) |

## Exploratory Data Analysis
